name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    permissions: write-all
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version-file: .node-version
        # explicitly install playwright to reduce chance of hangs 
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Build, Lint, Test, and Typecheck
        run: pnpm run ci:full
      - name: Upload E2E report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/visualizer/playwright-report/
          retention-days: 30
      - name: Release
        uses: changesets/action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          version: pnpm run version
          publish: pnpm exec changeset publish
          commit: 'chore: release'
          title: 'chore: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
